/**
 * @file glps_common.h
 * @brief Common definitions and structures for GLPS.
 */

#ifndef GLPS_COMMON_H
#define GLPS_COMMON_H

// Standard C headers
#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
// Platform-specific includes
#ifdef GLPS_USE_WIN32
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0600 // Windows Vista or newer
#endif
#include <windows.h>
#include <winuser.h>
#include <tchar.h>
#include <wchar.h>
#include <shlwapi.h>
#include <winreg.h>
#include <shellapi.h>
#include <GL/gl.h>
#endif

#ifdef GLPS_USE_WAYLAND
#include <wayland-client.h>
#include <wayland-client-protocol.h>
#include <wayland-egl.h>
#include <EGL/egl.h>
#include <EGL/eglext.h>
#include <xkbcommon/xkbcommon.h>
#include <sys/mman.h>
// Wayland protocol extensions
#include "xdg/xdg-shell.h"
#include "xdg/xdg-decorations.h"
#include "xdg/xdg-toplevel-tag.h"
#include "xdg/wlr-data-control-unstable-v1.h"
#endif

#ifdef GLPS_USE_X11
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/X.h>
#include <X11/cursorfont.h>
#include <X11/extensions/shape.h>
#include <EGL/egl.h>
#include <EGL/eglext.h>

#endif

#ifdef GLPS_USE_VULKAN
#include <vulkan/vulkan.h>
#ifdef GLPS_USE_X11
#include <vulkan/vulkan_xlib.h>
#endif
#endif

// Common constants
#define MAX_WINDOWS 100

// Forward declarations and common types that don't depend on platform
typedef struct glps_WindowManager glps_WindowManager;
typedef struct glps_Callback glps_Callback;

/**
 * @enum GLPS_SCROLL_AXES
 * @brief Scroll axis definitions.
 */
typedef enum {
    GLPS_SCROLL_H_AXIS, /**< Horizontal scroll axis. */
    GLPS_SCROLL_V_AXIS  /**< Vertical scroll axis. */
} GLPS_SCROLL_AXES;

/**
 * @enum GLPS_SCROLL_SOURCE
 * @brief Scroll source definitions.
 */
typedef enum {
    GLPS_SCROLL_SOURCE_FINGER,     /**< Scroll generated by a finger. */
    GLPS_SCROLL_SOURCE_WHEEL,      /**< Scroll generated by a wheel. */
    GLPS_SCROLL_SOURCE_CONTINUOUS, /**< Continuous scrolling source. */
    GLPS_SCROLL_SOURCE_WHEEL_TILT, /**< Tilted wheel scroll source. */
    GLPS_SCROLL_SOURCE_OTHER       /**< Other scroll source. */
} GLPS_SCROLL_SOURCE;

/**
 * @enum GLPS_CURSOR_TYPE
 * @brief Cursor types.
 */
typedef enum {
    GLPS_CURSOR_ARROW,
    GLPS_CURSOR_IBEAM,
    GLPS_CURSOR_CROSSHAIR,
    GLPS_CURSOR_HAND,
    GLPS_CURSOR_HRESIZE,
    GLPS_CURSOR_VRESIZE,
    GLPS_CURSOR_NOT_ALLOWED
} GLPS_CURSOR_TYPE;

typedef enum {
    GLPS_WINDOW_NORMAL    = 0,
    GLPS_WINDOW_FRAMELESS = 1 << 0,
    GLPS_WINDOW_TRANSPARENT = 1 << 1
} GLPS_WindowFlags;

/**
 * @struct glps_WindowProperties
 * @brief Properties for a GLPS window.
 */
typedef struct {
    char title[64]; /**< Title of the window. */
    int width;
    int height;
} glps_WindowProperties;

/**
 * @struct glps_Callback
 * @brief Callback function pointers for window events.
 */
struct glps_Callback {
    // Keyboard events
    void (*keyboard_enter_callback)(size_t window_id, void *data);
    void (*keyboard_leave_callback)(size_t window_id, void *data);
    void (*keyboard_callback)(size_t window_id, bool state, const char *value,
                             unsigned long keycode, void *data);

    // Mouse events
    void (*mouse_enter_callback)(size_t window_id, double mouse_x, double mouse_y, void *data);
    void (*mouse_leave_callback)(size_t window_id, void *data);
    void (*mouse_move_callback)(size_t window_id, double mouse_x, double mouse_y, void *data);
    void (*mouse_click_callback)(size_t window_id, bool state, void *data);
    void (*mouse_scroll_callback)(size_t window_id, GLPS_SCROLL_AXES axe,
                                 GLPS_SCROLL_SOURCE source, double value,
                                 int discrete, bool is_stopped, void *data);

    // Touch events
    void (*touch_callback)(size_t window_id, int id, double touch_x, double touch_y,
                          bool state, double major, double minor, double orientation, void *data);

    // Drag & drop
    void (*drag_n_drop_callback)(size_t window_id, char *mime_type, char *data,
                                int x, int y, void *user_data);

    // Window events
    void (*window_resize_callback)(size_t window_id, int width, int height, void *data);
    void (*window_close_callback)(size_t window_id, void *data);
    void (*window_frame_update_callback)(size_t window_id, void *data);

    // User data for each callback
    void *mouse_enter_data;
    void *mouse_leave_data;
    void *mouse_move_data;
    void *mouse_click_data;
    void *mouse_scroll_data;
    void *keyboard_enter_data;
    void *keyboard_leave_data;
    void *keyboard_data;
    void *touch_data;
    void *drag_n_drop_data;
    void *window_resize_data;
    void *window_frame_update_data;
    void *window_close_data;
};

// Platform-specific structures
#ifdef GLPS_USE_WAYLAND

// Wayland event structures
enum pointer_event_mask {
    POINTER_EVENT_ENTER = 1 << 0,
    POINTER_EVENT_LEAVE = 1 << 1,
    POINTER_EVENT_MOTION = 1 << 2,
    POINTER_EVENT_BUTTON = 1 << 3,
    POINTER_EVENT_AXIS = 1 << 4,
    POINTER_EVENT_AXIS_SOURCE = 1 << 5,
    POINTER_EVENT_AXIS_STOP = 1 << 6,
    POINTER_EVENT_AXIS_DISCRETE = 1 << 7,
};

struct pointer_event {
    uint32_t event_mask;
    wl_fixed_t surface_x;
    wl_fixed_t surface_y;
    uint32_t button;
    uint32_t state;
    uint32_t time;
    uint32_t serial;
    struct {
        bool valid;
        wl_fixed_t value;
        int32_t discrete;
    } axes[2];
    uint32_t axis_source;
    size_t window_id;
};

enum touch_event_mask {
    TOUCH_EVENT_DOWN = 1 << 0,
    TOUCH_EVENT_UP = 1 << 1,
    TOUCH_EVENT_MOTION = 1 << 2,
    TOUCH_EVENT_CANCEL = 1 << 3,
    TOUCH_EVENT_SHAPE = 1 << 4,
    TOUCH_EVENT_ORIENTATION = 1 << 5,
};

struct touch_point {
    bool valid;
    int32_t id;
    uint32_t event_mask;
    wl_fixed_t surface_x;
    wl_fixed_t surface_y;
    wl_fixed_t major;
    wl_fixed_t minor;
    wl_fixed_t orientation;
};

struct touch_event {
    uint32_t event_mask;
    uint32_t time;
    uint32_t serial;
    struct touch_point points[10];
    size_t window_id;
};

typedef struct {
    int x;
    int y;
} glps_DropCoordinates;

typedef struct {
    struct xdg_surface *xdg_surface;
    struct xdg_toplevel *xdg_toplevel;
    struct wl_surface *wl_surface;
    EGLSurface egl_surface;
    struct wl_egl_window *egl_window;
    glps_WindowProperties properties;
    struct zxdg_toplevel_decoration_v1 *zxdg_toplevel_decoration;
    struct wl_callback *frame_callback;
    struct timespec fps_start_time;
    bool fps_is_init;
    void *frame_args;
    uint32_t serial;
} glps_WaylandWindow;

typedef struct {
    struct wl_display *wl_display;
    struct wl_registry *wl_registry;
    struct wl_compositor *wl_compositor;
    struct wl_seat *wl_seat;
    struct xdg_wm_base *xdg_wm_base;
    struct zxdg_decoration_manager_v1 *decoration_manager;
    struct xdg_toplevel_tag_manager_v1 *tag_manager;
    struct wl_data_device_manager *data_dvc_manager;
    struct wl_data_device *data_dvc;
    struct wl_data_source *data_src;
    struct wl_pointer *wl_pointer;
    struct wl_keyboard *wl_keyboard;
    struct xkb_state *xkb_state;
    struct xkb_context *xkb_context;
    struct xkb_keymap *xkb_keymap;
    struct wl_touch *wl_touch;
    struct wl_data_offer *current_drag_offer;
    uint32_t current_serial;
    uint32_t keyboard_serial;
    size_t keyboard_window_id;
    size_t mouse_window_id;
    size_t touch_window_id;
    size_t current_drag_n_drop_window;
    glps_DropCoordinates drop_coordinates;
} glps_WaylandContext;

#endif // GLPS_USE_WAYLAND

#if defined(GLPS_USE_WAYLAND) || defined(GLPS_USE_X11)
typedef struct {
    EGLDisplay dpy;
    EGLContext ctx;
    EGLConfig conf;
} glps_EGLContext;
#endif

#ifdef GLPS_USE_WIN32
typedef struct {
    HWND hwnd;
    HDC hdc;
    glps_WindowProperties properties;
    LARGE_INTEGER fps_start_time;
    LARGE_INTEGER fps_freq;
    bool fps_is_init;
} glps_Win32Window;

typedef struct {
    WNDCLASSEX wc;
    HGLRC hglrc;
    HCURSOR user_cursor;
} glps_Win32Context;
#endif

#ifdef GLPS_USE_X11
typedef struct {
    Display *display;
    GC gc;
    Atom wm_delete_window;
    XFontStruct *font;
    Cursor cursor;
} glps_X11Context;

typedef struct {
    EGLSurface egl_surface;
    struct wl_egl_window *egl_window;
    Window window;
    bool fps_is_init;
    struct timespec fps_start_time;
    bool is_desktop;
} glps_X11Window;
#endif

#ifdef GLPS_USE_VULKAN
typedef struct {
    uint32_t count;
    const char** names;
} glps_VulkanExtensionArray;
#endif

// Common utility structures
struct clipboard_data {
    char mime_type[64];
    char buff[1024];
};

struct glps_debug {
    bool enable_fps_counter;
};

/**
 * @struct glps_WindowManager
 * @brief Main window manager structure.
 */
struct glps_WindowManager {
    // Platform-specific contexts
#ifdef GLPS_USE_WAYLAND
    glps_WaylandContext *wayland_ctx;
    glps_WaylandWindow **windows;
    glps_EGLContext *egl_ctx;
    struct touch_event touch_event;
    struct pointer_event pointer_event;
    struct clipboard_data clipboard;
#endif

#ifdef GLPS_USE_WIN32
    glps_Win32Context *win32_ctx;
    glps_Win32Window **windows;
    WNDCLASSEX wc;
#endif

#ifdef GLPS_USE_X11
    glps_EGLContext *egl_ctx;
    glps_X11Context *x11_ctx;
    glps_X11Window **windows;
#endif

    // Common fields
    char font_path[256];
    size_t window_count;
    bool inhibit_reset;
    unsigned int selected_color;
    struct glps_debug debug_utilities;
    struct glps_Callback callbacks;
    bool should_close;
};

// Additional utility structures
typedef struct {
    glps_WindowManager *wm;
    size_t window_id;
} frame_callback_args;

typedef struct {
    void *thread;
    void *volume_mutex;
    void *state_mutex;
    const char *audio_file_path;
    const char *device_name;
    int buffer_frames;
    float *pcm_buffer;
    int sample_rate;
    int channels;
    int bits_per_sample;
    int buffer_size;
    float volume;
    int position;
    int is_playing;
    int is_paused;
    int is_stopped;
    void *pcm_handle;
    void *mp3;
} glps_audio_stream;

#endif /* GLPS_COMMON_H */
